/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Donte_Loves_Art (https://sketchfab.com/Donte_Loves_Art)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/female-body-type-a-dc7fa4ea4eca4ec89bd29bf8a2418033
Title: Female Body Type A
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group } from 'three'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'

export function FemaleBody(props: any) {
    const group = useRef<Group>(null)
    const { nodes, materials, animations } = useGLTF('/models/female_body_type_a.glb') as any
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        if (animations.length > 0) {
            actions[animations[0].name]?.play();
        }
    }, [actions, animations]);

    const yPosition = useMotionValue(5);
    const ySpring = useSpring(yPosition, { damping: 30 });
    useEffect(() => {
        ySpring.set(-1);
    }, [ySpring]);
    useFrame(() => {
        group.current!.position.y = ySpring.get();
    });
    return (
        <group
            ref={group}
            {...props}
            dispose={null}
            scale={props.scale || 1}
            position={props.position || [1.3, -1.5, 0]}
        >            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.753}>
                    <group
                        name="6bc132ef54a942d4978fec8021b7510bfbx"
                        rotation={[Math.PI / 2, 0, 0]}
                        scale={0.01}>
                        <group name="Object_2">
                            <group name="RootNode">
                                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                                    <group name="Object_5">
                                        <primitive object={nodes._rootJoint} />
                                        <skinnedMesh
                                            name="Object_82"
                                            geometry={nodes.Object_82.geometry}
                                            material={materials.shorts}
                                            skeleton={nodes.Object_82.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_84"
                                            geometry={nodes.Object_84.geometry}
                                            material={materials.skin}
                                            skeleton={nodes.Object_84.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_85"
                                            geometry={nodes.Object_85.geometry}
                                            material={materials.nails}
                                            skeleton={nodes.Object_85.skeleton}
                                        />
                                        <skinnedMesh
                                            name="Object_87"
                                            geometry={nodes.Object_87.geometry}
                                            material={materials.shirt}
                                            skeleton={nodes.Object_87.skeleton}
                                        />
                                        <group name="Object_81" />
                                        <group name="Object_83" />
                                        <group name="Object_86" />
                                    </group>
                                </group>
                                <group name="shorts" />
                                <group name="body" />
                                <group name="shirt" />
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/female_body_type_a.glb')
