/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Emerald_knight (https://sketchfab.com/Emerald_knight)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/whirlwind-mutant-breeze-48e283c8fd3647e4befc27fddc5e6576
Title: Whirlwind (mutant breeze)
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { Group } from 'three'
import { useMotionValue, useSpring } from 'motion/react'
import { useFrame } from '@react-three/fiber'

export function Motants(props: any) {
  const group = useRef<Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/whirlwind_mutant_breeze.glb') as any
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    if (animations.length > 0) {
      actions[animations[0].name]?.play();
    }
  }, [actions, animations]);

  const yPosition = useMotionValue(5);
  const ySpring = useSpring(yPosition, { damping: 30 });
  useEffect(() => {
    ySpring.set(-1);
  }, [ySpring]);
  useFrame(() => {
    group.current!.position.y = ySpring.get();
  })
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={props.scale || 1}
      position={props.position || [1.3, -1.5, 0]}
    >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, -Math.PI]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_28">
                <group name="head_2" position={[0, 1.969, 0]}>
                  <group name="head_0" position={[0, -1.969, 0]}>
                    <mesh
                      name="Object_6"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_6.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="head_1" position={[0, -1.969, 0]}>
                    <mesh
                      name="Object_8"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_8.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="Middle_6">
                  <group name="rotater2_3">
                    <mesh
                      name="Object_11"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_11.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="rotater3_4" rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
                    <mesh
                      name="Object_13"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_13.geometry}
                      material={materials.material_0}
                    />
                  </group>
                  <group name="rotater4_5" rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
                    <mesh
                      name="Object_15"
                      castShadow
                      receiveShadow
                      geometry={nodes.Object_15.geometry}
                      material={materials.material_0}
                    />
                  </group>
                </group>
                <group name="Outside_22">
                  <group name="upperBodyParts1_11" position={[0, 1, 0]}>
                    <group name="rotater1_8" position={[0, 0, -0.75]}>
                      <group
                        name="rotater1_7"
                        position={[0, -0.188, 0]}
                        rotation={[-Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_20"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_20.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="bone3_10">
                      <group
                        name="rotater3_9"
                        position={[0, 0.188, -0.75]}
                        rotation={[Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_23"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_23.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="upperBodyParts2_16"
                    position={[0, 1, 0]}
                    rotation={[-Math.PI, -Math.PI / 4, -Math.PI]}>
                    <group name="rotater2_13" position={[0, 0, -0.75]}>
                      <group
                        name="rotater3_12"
                        position={[0, -0.188, 0]}
                        rotation={[-Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_27"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_27.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="bone4_15">
                      <group
                        name="rotater2_14"
                        position={[0, 0.188, -0.75]}
                        rotation={[Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_30"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_30.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="upperBodyParts5_21"
                    position={[0, 1, 0]}
                    rotation={[-Math.PI, Math.PI / 4, -Math.PI]}>
                    <group name="rotater3_18" position={[0, 0, -0.75]}>
                      <group
                        name="rotater4_17"
                        position={[0, -0.188, 0]}
                        rotation={[-Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_34"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_34.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group name="bone5_20">
                      <group
                        name="rotater3_19"
                        position={[0, 0.188, -0.75]}
                        rotation={[Math.PI / 8, 0, 0]}>
                        <mesh
                          name="Object_37"
                          castShadow
                          receiveShadow
                          geometry={nodes.Object_37.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Storm_charge_27">
                  <group name="Wind_24" position={[0, 1.188, 0]}>
                    <group name="cube_23" position={[-0.188, -0.125, -0.188]}>
                      <mesh
                        name="Object_41"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_41.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                  <group name="Charge_26">
                    <group name="cube_25" position={[-0.25, 1, -0.25]}>
                      <mesh
                        name="Object_44"
                        castShadow
                        receiveShadow
                        geometry={nodes.Object_44.geometry}
                        material={materials.material_0}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/whirlwind_mutant_breeze.glb')